### ISSUE TITLE
C Size unit price is offset to the right

### ISSUE THREAD

**Issue by drewciaramitaro** [drewciaramitaro/qsbulkprint#4]
Caused simply by the div width being too high

**Comment by Tdzie** [comment]
This might be an issue on my side. Let me know if it’s consistent across the applications and I’ll modify my css file for c sized signs.

**Comment by drewciaramitaro** [comment]
> This might be an issue on my side. Let me know if it’s consistent across the applications and I’ll modify my css file for c sized signs. 

Nah, I modified it myself in my override because the "you save" was too far to the left (i made the bottom section out of pure html&css as opposed to using the image used on QuickSign - given that we could be loading a ton of signs at once -- _i printed about 140 C signs today alone at 240_ -- doing it just in html/css was deemed worth it due to how underpowered our store PCs are), so I went too far in the wrong direction. Simple fix on my end, appears good on regular quicksign
