### ISSUE TITLE
Show user how many signs will be printed prior to printing

### ISSUE THREAD

**Issue by drewciaramitaro** [drewciaramitaro/qsbulkprint#6]
This will let the teammate know how many signs to load into the printer (as mentioned by Tim in #2)

_Possibly a popup would work fine once you hit print? or just show it dynamically in the top toolbar_

**Comment by Tdzie** [comment]
A pop-up when you hit print is the easiest option.  Like you said in your other comment, does the user need to taken another action inside the pop to make the final print. I say it’s important! If not, the windows print box will block it from view of the user.  
A confirmation alert might do the trick and the actual print command activates on confirmation. 

Dynamic is a fun option but remember to modify the number when user adds header sections or deletes signs. Also, this option doesn’t have a check before the final print.  

Have you seen or personally printed a sign with the wrong paper size or none at all? What would help prevent this action?

You could go as far as to explain that the user is about to print x amount of b/c sized signs with a image of the correct sized sign facing the right way in the tray of one of our printers. Then make the user confirm before printing.

**Comment by drewciaramitaro** [comment]
>  does the user need to taken another action inside the pop to make the final print.

Yes, that was what I had in mind


> Have you seen or personally printed a sign with the wrong paper size or none at all? What would help prevent this action?

I haven't, but I like the idea of showing the right way
